name: Frontend CI/CD

on:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"
  pull_request:
    branches: ["main"]
    paths:
      - "frontend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          docker login --username ${{github.actor}} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker build ./frontend/ --file ./frontend/Dockerfile --platform linux/amd64 --tag ghcr.io/polytechnique-school-work/conuhacks_frontend:latest
          docker push ghcr.io/polytechnique-school-work/conuhacks_frontend:latest

      - name: Run Tests
        run: |
          cd backend
          # TODO: Add tests
